name: CI
on:
  pull_request:
    branches:
      - production

jobs:
  hello:
    if: github.base_ref == 'production'
    runs-on: ubuntu-latest
    steps:
      - run: echo "current branch is production"
