name: CI
on:
  pull_request:
    branches:
      - production

jobs:
  hello:
    if: github.base_ref == 'production'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{secrets.CLOUDFRONT_ID}}"
      - run: echo "hehe ${{secrets.HEHE}}"
  bye:
    if: github.base_ref == 'main'
    uses: ./.github/workflows/bye.yml
